# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59a87ea98fb9b41233cd888d6d161cbeae7558f6291b804beae8b5106363f7fd5e5f01f6951287d5d44e4124ba5aaca1478a446eb28952bfcc32402a18d12a3

test:
  secret_key_base: c2cd96b1f5a876106efe6db9b057da8409665ce65a54569b43852c91fd3d58c984245214ba82c465d586286459c92505ca6bbfd12d36274099830ddaa6f36def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
